"""add projects, client_tokens.project_id and users.is_admin

Revision ID: 4600d2ec79c8
Revises: 206bb5df3327
Create Date: 2026-04-11 06:04:36.890448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4600d2ec79c8'
down_revision: Union[str, Sequence[str], None] = '206bb5df3327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client_tokens', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_client_tokens_project_id'), 'client_tokens', ['project_id'], unique=False)
    op.create_foreign_key(
        'client_tokens_project_id_fkey',
        'client_tokens', 'projects', ['project_id'], ['id'], ondelete='CASCADE',
    )
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint('client_tokens_project_id_fkey', 'client_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_client_tokens_project_id'), table_name='client_tokens')
    op.drop_column('client_tokens', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
