"""add project summary

Revision ID: 678e1d678a82
Revises: 4600d2ec79c8
Create Date: 2026-04-11 06:31:36.245424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678e1d678a82'
down_revision: Union[str, Sequence[str], None] = '4600d2ec79c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('projects', sa.Column('summary', sa.String(length=300), nullable=True))
    op.execute(
        "UPDATE projects SET summary = substr(description, 1, 300) WHERE summary IS NULL"
    )
    op.alter_column('projects', 'summary', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'summary')
    # ### end Alembic commands ###
